apiVersion: v1
kind: PersistentVolume
metadata:
name: free5gc-pv-cert
labels:
    project: free5gc
spec:
capacity:
    storage: 2Mi
accessModes:
- ReadOnlyMany
persistentVolumeReclaimPolicy: Retain
storageClassName: microk8s-hostpath
local:
    path: /home/vagrant/certs
nodeAffinity:
    required:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
        operator: In
        values:
        - worker-1

