apiVersion: v1
kind: PersistentVolume
metadata:
  name: emqx-broker
  namespace: default
  labels:
    type: local
spec:
  # storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-volume-claim
  namespace: default
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: emqx-broker
