apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-broker
  namespace: mosquitto-service
  labels:
    type: local
spec:
  # storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"
